if [ $DISTRO_BASE = Debian ] ; then
  aliases[binutils]=$DISTRO:binutils
  aliases[bzip2]=$DISTRO:bzip2
  aliases[cabextract]=$DISTRO:cabextract
  aliases[cpio]=$DISTRO:cpio
  aliases[gnu_tar]=$DISTRO:tar
  aliases[gzip]=$DISTRO:gzip
  aliases[lhasa]=$DISTRO:lhasa
  aliases[macutils]=$DISTRO:macutils
  aliases[7-Zip]=$DISTRO:p7zip-full
  aliases[p7zip-rar]=$DISTRO:p7zip-rar
  aliases[pax]=$DISTRO:pax
  aliases[pbzip2]=$DISTRO:pbzip2
  aliases[pigz]=$DISTRO:pigz
  aliases[pixz]=$DISTRO:pixz
  aliases[tar]=$DISTRO:tar
  aliases[unar]=$DISTRO:unar
  aliases[unrar]=$DISTRO:unrar
  aliases[unzip]=$DISTRO:unzip
  aliases[xz]=$DISTRO:xz
  aliases[zip]=$DISTRO:zip
  aliases[zstandard]=$DISTRO:zstd
  aliases[arj]=$DISTRO:arj
  aliases[lzip]=$DISTRO:lzip  # Does both
  aliases[lunzip]=$DISTRO:lunzip
  aliases[compress]=$DISTRO:ncompress
  aliases[dictzip]=$DISTRO:dictzip
fi
